version: '1.0'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
  sentence_transformers_serving:
    container_name: sentence_transformers_serving
    build: .
    ports:
      - "5002:5000"
    environment:
      - MODEL=sentence-transformers/sentence-t5-base